{"uuid": "1238f9f2-cf4f-4853-bfbe-a3068e5249c4", "children": ["f6e624ec-33b9-4700-a7f2-837858fe6004", "a16f9a8f-516d-40d6-b94a-10fa934acb7a", "c3910e4f-0489-4b96-aa88-1e235087a65f", "ffce55cf-7e64-4607-adb2-d0669a1841b9"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719633877, "stop": 1657719641774}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719649646, "stop": 1657719649651}], "start": 1657719633877, "stop": 1657719649651}