{"uuid": "8af39d4c-7937-4eb5-a9f9-095a1aafb18d", "children": ["d3a6ff51-000f-43a8-ba61-6b9a5ac14b99", "d10ed35c-49dc-4138-ba6a-9fd65ef084d0", "97e44d6e-51d2-47ee-a10a-bd7a0287f791"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719633877, "stop": 1657719643212}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719650686, "stop": 1657719650687}], "start": 1657719633877, "stop": 1657719650687}