{"uuid": "a76ff598-2099-431a-b8b2-3555ace582c6", "children": ["e07a4313-9d1c-4226-a2b6-0bbd310c966e"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720343728, "stop": 1657720371430}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720373189, "stop": 1657720373189}], "start": 1657720343728, "stop": 1657720373189}