{"uuid": "46e83c16-860b-44df-9110-70b7cb8ea210", "children": ["c045a878-cd4c-4f90-a89b-70aea168ba6e", "22fac03f-dfee-43a3-ac61-48f17c611e61"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720715945, "stop": 1657720721040}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720722820, "stop": 1657720722821}], "start": 1657720715945, "stop": 1657720722821}