{"uuid": "db5ae5a5-5728-43bd-a625-fa2c58cabefe", "children": ["88a4c095-382a-4c28-8e4f-6490250c959c"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719665957, "stop": 1657719676169}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719678341, "stop": 1657719678347}], "start": 1657719665957, "stop": 1657719678347}