{"uuid": "ffab62ff-2f04-45e6-880e-3375c786c346", "children": ["f88e3c9b-5201-4199-a2f5-072378ad61e4"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720303651, "stop": 1657720323156}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720343663, "stop": 1657720343665}], "start": 1657720303651, "stop": 1657720343665}