{"uuid": "e66c9616-6ffa-4e95-ba77-445a112b79d8", "children": ["d78613de-d6f9-4e06-ad06-1bd3f1c7868d"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719665807, "stop": 1657719676154}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719678401, "stop": 1657719678401}], "start": 1657719665807, "stop": 1657719678401}