{"uuid": "08a61cf1-2146-45a5-84a4-427005d15548", "children": ["53f7452b-c461-45a9-882b-ed11d75b0798", "0254d2bd-573a-4fac-8983-bf541b08fb80"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720704128, "stop": 1657720729232}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720731692, "stop": 1657720731692}], "start": 1657720704128, "stop": 1657720731692}