{"uuid": "ecb88cad-1a4c-46e3-a3c8-a3f967bbf575", "children": ["15e47ed9-46cf-4b23-906c-5794f8b084b9", "f3cf3530-28fd-413f-9794-65a7c8be75d0", "5bb17b8f-5129-4d14-ad89-cf2eb8fd84d5", "ce6d2e0f-57b5-4053-8bd4-fbb458f796c8", "16f054fd-ae4f-4b33-9ce3-3a85dd15be21", "e3106212-4b67-4fa7-8518-6f092e3746f9"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720687873, "stop": 1657720704028}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720765663, "stop": 1657720765663}], "start": 1657720687873, "stop": 1657720765663}